before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
language: java
script:
  - java -version
  - javac -version
  - mkdir out
  - javac -cp ./src:./out:./junit.jar -d ./out ./src/Model/*.java ./test/Model/*.java
  - java -cp ./out:./junit.jar:./out/Model Model.AuLongCoursTest
  - java -cp ./out:./junit.jar:./out/Model Model.CategorieTest
  - java -cp ./out:./junit.jar:./out/Model Model.PonctuelleTest
  - java -cp ./out:./junit.jar:./out/Model Model.TacheTest

